letter:
  sender:
    error-strategy: fail
  processing:
    overflow-strategy: terminate



spring:
  devtools:
    livereload:
      enabled: false

io.rsocket.routing.client:
  route-id: ${random.uuid}
  service-name: ${spring.cloud.consul.discovery.service-name}
  tags:
    INSTANCE_NAME: ${spring.application.name}
  brokers:
    - host: localhost
      port: 8002