letter:
  receiver:
    base-url: http://localhost:8080/
  processing:
    time: 2000
    random-delay: 1000
    queue-size: 10
    concurrency-level: 2








server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.boot.devtools.autoconfigure: DEBUG

spring:
  application:
    order: 2
    name: agent-smith-service
  devtools:
    livereload:
      port: 10510
