letter:
  receiver:
    service-name: pechkin-service
  processing:
    time: 2000
    random-delay: 1000
    queue-size: 10
    concurrency-level: 2


server:
  port: 8082

spring:
  application:
    order: 2
    name: agent-smith-service
  cloud:
    consul:
      discovery:
        instance-group: agent-smith-service
        service-name: agent-smith-service
