letter:
  receiver:
    base-url: http://localhost:8082/
  processing:
    time: 500
    random-delay: 0
    queue-size: 100
    concurrency-level: 8


server:
  port: 8081

spring:
  application:
    order: 1
    name: big-bro-service
