letter:
  receiver:
    service-name: agent-smith-service
  processing:
    time: 500
    random-delay: 0
    queue-size: 100
    concurrency-level: 8


server:
  port: 8081

spring:
  application:
    order: 1
    name: big-bro-service
  cloud:
    consul:
      discovery:
        instance-group: big-bro-service
        service-name: big-bro-service
