letter:
  receiver:
    base-url: http://localhost:8081/
  processing:
    time: 0
    random-delay: 0
    queue-size: 100
    concurrency-level: 1
    overflow-strategy: block


server:
  port: 8080

spring:
  application:
    order: 0
    name: pechkin-service
